/**
 * Generated by Apache Flex Cross-Compiler from Test_BunnyMark.as
 * Test_BunnyMark
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('Test_BunnyMark');

goog.require('bunnyMark.BackGround');
goog.require('bunnyMark.BunnyTileTest');
goog.require('org.apache.flex.utils.Language');



/**
 * @usage this is used for configing emsc module.
 *
 * <inject_html>
 * <script type="text/javascript">
 * 		ajcGlobal.emscModuleFileName = "AjcRuntimeWeb";
 *		ajcGlobal.emscOutputModuleName = "flash";
 *		ajcGlobal.emscSrcEmscModuleName = "AjcRuntimeWeb";
 *		ajcGlobal.emscModuleConfig = {};
 * 		ajcGlobal.emscModuleAdditionalMainArgs = "";
 *
 *      ajcGlobal.stageInitWidth = 1280;
 * 		ajcGlobal.stageInitHeight = 700;
 * 		ajcGlobal.stageAutoSize = true;
 * 	    ajcGlobal.useStageMinSize = true;
 *
 * </script>
 * </inject_html>
 * @constructor
 * @extends {flash.display.Sprite}
 */
Test_BunnyMark = function() {
  Test_BunnyMark.base(this, 'constructor');
  if (this.stage)
    this.init(null);
  else
    this.addEventListener(flash.events.Event.ADDED_TO_STAGE, org.apache.flex.utils.Language.closure(this.init, this, 'init'), false, 0, false);
};
goog.inherits(Test_BunnyMark, flash.display.Sprite, 'Test_BunnyMark');


/**
 * @private
 * @param {flash.events.Event} e
 */
Test_BunnyMark.prototype.init = function(e) {
  this.removeEventListener(flash.events.Event.ADDED_TO_STAGE, org.apache.flex.utils.Language.closure(this.init, this, 'init'), false);
  this.addChild(new bunnyMark.BackGround());
  this.addChild(new bunnyMark.BunnyTileTest(5000));
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
Test_BunnyMark.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'Test_BunnyMark', qName: 'Test_BunnyMark', kind: 'class' }] };


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('Test_BunnyMark', Test_BunnyMark);



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
Test_BunnyMark.prototype.FLEXJS_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'Test_BunnyMark': { type: '', declaredBy: 'Test_BunnyMark'}
      };
    }
  };
};

//# sourceMappingURL=./Test_BunnyMark.js.map