/**
 * Generated by Apache Flex Cross-Compiler from bunnyMark\Bunny.as
 * bunnyMark.Bunny
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('bunnyMark.Bunny');
goog.require('org.apache.flex.utils.Language');



/**
 * @constructor
 * @extends {flash.display.Bitmap}
 * @param {flash.display.BitmapData} bitmapData
 */
bunnyMark.Bunny = function(bitmapData) {
  bunnyMark.Bunny.base(this, 'constructor', bitmapData);
  this.speedX = 0;
  this.speedY = 0;
};
goog.inherits(bunnyMark.Bunny, flash.display.Bitmap, 'bunnyMark.Bunny');


/**
 * @export
 * @type {number}
 */
bunnyMark.Bunny.prototype.speedX;


/**
 * @export
 * @type {number}
 */
bunnyMark.Bunny.prototype.speedY;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
bunnyMark.Bunny.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'Bunny', qName: 'bunnyMark.Bunny', kind: 'class' }] };


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('bunnyMark.Bunny', bunnyMark.Bunny);



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
bunnyMark.Bunny.prototype.FLEXJS_REFLECTION_INFO = function () {
  return {
    variables: function () {
      return {
        'speedX': { type: 'Number'},
        'speedY': { type: 'Number'}
      };
    },
    accessors: function () {return {};},
    methods: function () {
      return {
        'Bunny': { type: '', declaredBy: 'bunnyMark.Bunny', parameters: function () { return [  { index: 1, type: 'flash.display.BitmapData', optional: false } ]; }}
      };
    }
  };
};

//# sourceMappingURL=./Bunny.js.map