/**
 * Generated by Apache Flex Cross-Compiler from Test_BunnyMark_Native.as
 * Test_BunnyMark_Native
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('Test_BunnyMark_Native');




/**
 * @usage this is used for configing emsc module.
 *
 * <inject_html>
 * <script type="text/javascript">
 * 		ajcGlobal.emscModuleFileName = "AjcRuntimeWeb";
 *		ajcGlobal.emscOutputModuleName = "flash";
 *		ajcGlobal.emscSrcEmscModuleName = "AjcRuntimeWeb";
 *		ajcGlobal.emscModuleConfig = {};
 * 		ajcGlobal.emscModuleAdditionalMainArgs = "";
 *
 *      ajcGlobal.stageInitWidth = 1280;
 * 		ajcGlobal.stageInitHeight = 700;
 * 		ajcGlobal.stageAutoSize = true;
 * 	    ajcGlobal.useStageMinSize = true;
 *
 * </script>
 * </inject_html>
 * @constructor
 * @extends {flash.display.Sprite}
 */
Test_BunnyMark_Native = function() {
  Test_BunnyMark_Native.base(this, 'constructor');
  var /** @type {*} */ wasmModual = window["flash"];
  wasmModual["RunBunnyTest"](20000);
};
goog.inherits(Test_BunnyMark_Native, flash.display.Sprite, 'Test_BunnyMark_Native');


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
Test_BunnyMark_Native.prototype.FLEXJS_CLASS_INFO = { names: [{ name: 'Test_BunnyMark_Native', qName: 'Test_BunnyMark_Native', kind: 'class' }] };


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('Test_BunnyMark_Native', Test_BunnyMark_Native);



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
Test_BunnyMark_Native.prototype.FLEXJS_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'Test_BunnyMark_Native': { type: '', declaredBy: 'Test_BunnyMark_Native'}
      };
    }
  };
};

//# sourceMappingURL=./Test_BunnyMark_Native.js.map